#!/usr/bin/bash
hdfs dfs -rm -r /user/s1115104/data/output/exc-cw2/s1115104_task_6_small.out

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -D mapred.reduce.tasks=5 \
 -input /data/assignments/ex2/task1/small/ \
 -output /user/s1115104/data/output/exc-cw2/s1115104_task_6_small.out \
 -mapper mapper.py \
 -file mapper.py \
 -combiner combiner.py \
 -file combiner.py \
 -reducer reducer.py \
 -file reducer.py \
 -jobconf mapred.job.name="Inverted Index S"

