#!/usr/bin/bash
hdfs dfs -rm -r /user/s1115104/data/output/exc-cw2/s1115104_task_6_small.out

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -D mapred.reduce.tasks=5 \
 -D mapreduce.job.output.key.comparator.class=org.apache.hadoop.mapreduce.lib.partition.KeyFieldBasedComparator \
 -D stream.num.map.output.key.fields=2 \
 -D num.key.fields.for.partition=1 \
 -D mapreduce.partition.keypartitioner.options=-k1,1 \
 -D mapreduce.partition.keycomparator.options="-k1,1r -k2,2"
 -input /data/assignments/ex2/task1/small/ \
 -output /user/s1115104/data/output/exc-cw2/s1115104_task_6_small.out \
 -mapper mapper.py \
 -file mapper.py \
 -combiner combiner.py \
 -file combiner.py \
 -jobconf mapred.job.name="Inverted Index S" \
 -partitioner org.apache.hadoop.mapred.lib.KeyFieldBasedPartitioner \

# -reducer reducer.py \
#  -file reducer.py \

hdfs dfs -cat /user/s1115104/data/output/exc-cw2/s1115104_task_6_small.out/part-00001 | head -n 100