#!/usr/bin/bash

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -input /user/$USER/data/output/lower-case-small \
 -output /user/$USER/data/output/deduplicated-small \
 -mapper mapper.py \
 -file mapper.py \
 -reducer reducer.py \
 -file reducer.py \
 -jobconf mapred.job.name="Deduplicated Small `echo $USER`"

 hdfs dfs -ls /user/$USER/data/output/deduplicated-small
