#!/usr/bin/bash

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -D mapred.reduce.tasks=1 \
 -input /user/$USER/data/output/task4-small \
 -output /user/$USER/data/output/task6-small \
 -mapper most_common.py \
 -file most_common.py \
 -reducer most_common.py \
 -jobconf mapred.job.name="Most Common Small `echo $USER`"

hdfs dfs -ls /user/$USER/data/output/task6-small

echo "Expected:"
echo "________________________________"
hdfs dfs -cat /data/assignments/samples/task_6.out/part-*

echo "Computed:"
echo "________________________________"
hdfs dfs -cat /user/$USER/data/output/task6-small/part-*

