#!/usr/bin/bash

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -input /user/$USER/data/output/deduplicated-small \
 -output /user/$USER/data/output/wc-small \
 -mapper mapper.py \
 -file mapper.py \
 -reducer reducer.py \
 -file reducer.py \
 -jobconf mapred.job.name="Word Count Small `echo $USER`"

echo "Expected Values: "
hdfs dfs -cat /data/assignments/samples/task_3.out/part-00000

echo "Produced Values: "
hdfs dfs -cat /user/$USER/data/output/wc-small/part-00000
