#!/usr/bin/bash

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -input /user/$USER/data/output/deduplicated \
 -output /user/$USER/data/output/wc \
 -mapper mapper.py \
 -file mapper.py \
 -reducer reducer.py \
 -file reducer.py \
 -jobconf mapred.job.name="Word Count Large `echo $USER`"

# TODO: Copy output to unix