#!/usr/bin/bash

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -D mapred.reduce.tasks=1
 -input /user/$USER/data/output/task8-small/ \
 -output /user/$USER/data/output/task9-small \
 -mapper mapper.py \
 -file mapper.py \
 -reducer reducer.py \
 -file reducer.py \
 -jobconf mapred.job.name="Lowest Average Small `echo $USER`"

hdfs dfs -ls /user/$USER/data/output/task9-small

echo "Expected WC: `hdfs dfs -cat /data/assignments/samples/task_9.out/part-* | wc`"
echo "Produced WC: `hdfs dfs -cat /user/$USER/data/output/task9-small/part-* | wc`"

