#!/usr/bin/bash

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -input /data/assignments/ex1/webLarge.txt \
 -output /user/$USER/data/output/lower-case \
 -mapper mapper.py \
 -file mapper.py \
 -jobconf mapred.job.name="Lower-case Large `echo $USER`"