#!/usr/bin/bash
hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -D mapred.reduce.tasks=0 \
 -input /data/assignments/ex1/webLarge.txt \
 -output /user/s1115104/data/output/exc-cw1/s1115104_task_1.out \
 -mapper mapper.py \
 -file mapper.py \
 -jobconf mapred.job.name="Lower-case Large s1115104"

echo "---------------------"

hdfs dfs -cat /user/s1115104/data/output/exc-cw1/s1115104_task_1.out/part-* | head -20