#!/usr/bin/bash

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -D mapred.reduce.tasks=1 \
 -input /user/s1115104/data/output/exc-cw1/s1115104_task_8.out \
 -output /user/s1115104/data/output/exc-cw1/s1115104_task_9.out \
 -mapper mapper.py \
 -file mapper.py \
 -reducer reducer.py \
 -file reducer.py \
 -jobconf mapred.job.name="Lowest Average Large s1115104"

hdfs dfs -cat /user/s1115104/data/output/exc-cw1/s1115104_task_9.out/part-* | head -n 20 > head20.out