#!/usr/bin/bash

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -input /user/$USER/data/output/task5-small \
 -output /user/$USER/data/output/task6-small \
 -mapper mapper.py \
 -file mapper.py \
 -reducer reducer.py \
 -file reducer.py \
 -jobconf mapred.map.tasks=32 \
 -jobconf mapred.job.reduces=1 \
 -jobconf mapred.job.name="Most Common Small `echo $USER`"

hdfs dfs -ls /user/$USER/data/output/task6-small

echo "Expected:"
echo "________________________________"
hdfs dfs -cat /data/assignments/samples/task_6.out/part-*

echo "Computed:"
echo "________________________________"
hdfs dfs -cat /user/$USER/data/output/task6-small/part-*

