#!/usr/bin/bash

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -D mapred.reduce.tasks=64 \
 -D mapreduce.job.output.key.comparator.class=org.apache.hadoop.mapreduce.lib.partition.KeyFieldBasedComparator \
 -D stream.num.map.output.key.fields=2 \
 -D num.key.fields.for.partition=1 \
 -D mapreduce.partition.keycomparator.options="-k1n -k2r" \
 -input /data/assignments/ex1/uniLarge.txt \
 -output /user/s1115104/data/output/exc-cw1/s1115104_task_8.out \
 -mapper mapper.py \
 -file mapper.py \
 -reducer reducer.py \
 -file reducer.py \
 -combiner combiner.py \
 -file combiner.py \
 -partitioner org.apache.hadoop.mapred.lib.KeyFieldBasedPartitioner \
 -jobconf mapred.job.name="Students Join Large `echo $USER`"

hdfs dfs -cat /user/s1115104/data/output/exc-cw1/s1115104_task_8.out/part-* | head -n 20 > head20.out