#!/bin/bash

export EXC2_4_2_INPUT=/data/assignments/ex2/task3/stackLarge.txt
export EXC2_4_2_OUTPUT=/user/s1115104/data/output/exc-cw2/s1115104_task_4_2.out

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
    -D mapred.job.name="WANTED: StackOverflow superhero! EXC 2 4-2 L" \
    -D mapred.reduce.tasks=1 \
    -input $EXC2_4_2_INPUT \
    -output $EXC2_4_2_OUTPUT \
    -mapper mapper.py \
    -combiner combiner.py \
    -reducer reducer.py \
    -file mapper.py \
    -file combiner.py \
    -file reducer.py

hdfs dfs -cat $EXC2_4_2_OUTPUT/part-* | head -n 10 > results.txt

