#!/bin/bash

export EXC2_3_3_INPUT=/data/assignments/ex2/task2/logsSmall.txt
export EXC2_3_3_OUTPUT=/user/s1115104/data/output/exc-cw2/s1115104_task_3_3_small.out

# Clean up
hdfs dfs -rm -r $EXC2_3_3_OUTPUT

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
    -D mapred.reduce.tasks=16 \
    -D mapreduce.job.output.key.comparator.class=org.apache.hadoop.mapreduce.lib.partition.KeyFieldBasedComparator \
    -D stream.num.map.output.key.fields=1 \
    -D num.key.fields.for.partition=1 \
    -D mapreduce.partition.keypartitioner.options=-k1,1 \
    -D mapreduce.partition.keycomparator.options="-k1,1 -k2,2n" \
    -D mapreduce.map.output.key.field.separator=" " \
    -input $EXC2_3_3_INPUT \
    -output $EXC2_3_3_OUTPUT \
    -mapper mapper.py \
    -combiner combiner.py \
    -reducer reducer.py \
    -file mapper.py \
    -file combiner.py \
    -file reducer.py \
    -jobconf mapred.job.name="How long did you stay around? EXC2 3.3 S" \
    -partitioner org.apache.hadoop.mapred.lib.KeyFieldBasedPartitioner

hdfs dfs -cat $EXC2_3_3_OUTPUT/part-* | head -n 10

