#!/bin/bash

echo "No output means all good."
echo "#########################"

diff md/example1.md md/solution1.md
diff md/example2.md md/solution2.md
diff md/example3.md md/solution3.md
diff md/example4.md md/solution4.md

diff latex/example1.latex latex/solution1.latex
diff latex/example2.latex latex/solution2.latex
diff latex/example3.latex latex/solution3.latex
diff latex/example4.latex latex/solution4.latex

diff html/example1.html html/solution1.html
diff html/example2.html html/solution2.html
diff html/example3.html html/solution3.html
diff html/example4.html html/solution4.html