#!/bin/bash

echo "No output means all good."
echo "#########################"

for format in "md" "latex" "html"
    do
        for i in {1..4}
            do
                EXAMPLE=$format/example$i.$format
                SOLUTION=$format/solution$i.$format

                echo "diff $EXAMPLE $SOLUTION"
                diff $EXAMPLE $SOLUTION
                echo "___________________________"
        done

done