#!/usr/bin/bash

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -D mapred.reduce.tasks=32 \
 -input /user/$USER/data/output/deduplicated-small \
 -output /user/$USER/data/output/task5-small \
 -mapper mapper.py \
 -file mapper.py \
 -reducer reducer.py \
 -file reducer.py \
 -combiner combiner.py \
 -file combiner.py \
 -jobconf mapred.job.name="Tuples Small Combiner `echo $USER`"

hdfs dfs -ls /user/$USER/data/output/task5-small

echo "Expected WC: `hdfs dfs -cat /data/assignments/samples/task_5.out/part-00000 | wc -l`"
echo "Produced WC: `hdfs dfs -cat /user/$USER/data/output/task5-small/part-* | wc -l`"

