#!/usr/bin/bash

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -input /user/$USER/data/output/deduplicated-small \
 -output /user/$USER/data/output/task5-small \
 -mapper mapper.py \
 -file mapper.py \
 -reducer reducer.py \
 -file reducer.py \
 -combiner combiner.py \
 -file combiner.py \
 -D mapred.map.tasks=16 \
 -D mapred.job.reduces=16 \
 -jobconf mapred.job.name="Bigrams Combiner Small `echo $USER`"

 hdfs dfs -ls /user/$USER/data/output/task5-small
