#!/usr/bin/bash

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -input /data/assignments/ex1/matrixSmall.txt \
 -output /user/$USER/data/output/task7-small \
 -mapper mapper.py \
 -file mapper.py \
 -reducer reducer.py \
 -file reducer.py \
 -jobconf mapred.map.tasks=32 \
 -jobconf mapred.job.reduces=8 \
 -jobconf mapred.job.name="Matrix Transpose Small `echo $USER`"

hdfs dfs -ls /user/$USER/data/output/task7-small