#!/usr/bin/bash

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -D mapreduce.job.output.key.comparator.class=org.apache.hadoop.mapreduce.lib.partition.KeyFieldBasedComparator \
 -D stream.num.map.output.key.fields=2 \
 -D num.key.fields.for.partition=1 \
 -D mapreduce.partition.keycomparator.options="-k1n -k2n" \
 -input /data/assignments/ex1/matrixLarge.txt \
 -output /user/$USER/data/output/task7 \
 -mapper mapper.py \
 -file mapper.py \
 -reducer reducer.py \
 -file reducer.py \
 -partitioner org.apache.hadoop.mapred.lib.KeyFieldBasedPartitioner \
 -jobconf mapred.job.reduces=20 \
 -jobconf mapred.job.name="Matrix Transpose Large `echo $USER`"

hdfs dfs -ls /user/$USER/data/output/task7
