#!/usr/bin/bash

hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
 -D mapreduce.job.output.key.comparator.class=org.apache.hadoop.mapreduce.lib.partition.KeyFieldBasedComparator \
 -D stream.num.map.output.key.fields=2 \
 -D num.key.fields.for.partition=1 \
 -D mapreduce.partition.keypartitioner.options=k1n \
 -D mapreduce.partition.keycomparator.options=k2n \
 -input /data/assignments/ex1/matrixSmall.txt \
 -output /user/$USER/data/output/task7-small \
 -mapper mapper.py \
 -file mapper.py \
 -partitioner org.apache.hadoop.mapred.lib.KeyFieldBasedPartitioner
 -jobconf mapred.map.tasks=32 \
 -jobconf mapred.job.reduces=8 \
 -jobconf mapred.job.name="Matrix Transpose Small `echo $USER`"


# hadoop jar /opt/hadoop/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar \
#  -D stream.num.map.output.key.fields=2 \
#  -D mapreduce.partition.keycomparator.options="-k1,1n -k2,2n" \
#  -input /data/assignments/ex1/matrixSmall.txt \
#  -output /user/$USER/data/output/task7-small \
#  -mapper mapper.py \
#  -file mapper.py \
#  -reducer reducer.py \
#  -file reducer.py \
#  -jobconf mapred.map.tasks=32 \
#  -jobconf mapred.job.reduces=8 \
#  -jobconf mapred.job.name="Matrix Transpose Small `echo $USER`"

# hdfs dfs -ls /user/$USER/data/output/task7-small